# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8-openj9

    working_directory: ~/repo

    steps:
      - checkout
      - run: mvn -U clean package verify

